apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels: #can have as many labels as you want. can group pods
    env: development
    version: v1
spec:
  containers:
  - name: hello-ctr
    image: nigelpoulton/k8sbook:1.0
    ports:
    - containerPort: 8080
