apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2024-05-27T18:14:13Z"
  name: developer
  namespace: blue
  resourceVersion: "2575"
  uid: fae7fb72-0788-4513-94f2-d80e99056fe3
rules:
- apiGroups:
  - ""
  resourceNames:
  - dark-blue-app
  resources:
  - pods
  verbs:
  - get
  - watch
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create